### ISSUE TITLE
Implement command to read VIN number

### ISSUE THREAD

**Issue by jnsmith0274** [pires/obd-java-api#34] opened 2015-06-05 03:20 UTC
How about a command to read the VIN number (mode 09)?

**Comment by pires** [comment] 2015-06-05 09:29
Why not? Will gladly review a PR.

**Comment by anti43** [comment] 2015-06-08 19:57
@pires I have it anyway, will do PR tomorrow so you can close this then

**Comment by pires** [comment] 2015-06-08 20:18
@anti43 awesome!

**Comment by nomwerp** [comment] 2015-07-14 18:48
@pires it seems that the response is always "7F0912" for my car , even when all other command return "NO DATA" for example when car not powered, is this a bug?

**Comment by pires** [comment] 2015-07-14 20:21
Probably.

**Comment by anti43** [comment] 2015-07-15 06:55
@pires see https://github.com/pires/obd-java-api/pull/41
it was using just the first buffer chunk before which is always the same

**Comment by pires** [comment] 2015-07-15 12:00
Thank you @anti43! I probably screwed up when cherry-picking your commits before. 

Will release RC3 in a moment.

**Comment by pires** [comment] 2015-07-15 14:20
Tests are failing so I can't release RC3.

```
    Tests run: 42, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.154 sec <<< FAILURE!
    testValidSpeedMetricWithMessage(com.github.pires.obd.commands.ExtraMessagesTest)  Time elapsed: 0.011 sec  <<< FAILURE!
    com.github.pires.obd.exceptions.NonNumericResponseException: Error reading response: BUSINIT...410D40
    	at com.github.pires.obd.commands.ObdCommand.fillBuffer(ObdCommand.java:180)
    	at com.github.pires.obd.commands.ObdCommand.readResult(ObdCommand.java:163)
    	at com.github.pires.obd.commands.ExtraMessagesTest.testValidSpeedMetricWithMessage(ExtraMessagesTest.java:78)
```

**Comment by anti43** [comment] 2015-07-15 14:44
@pires IMO the "BUS INIT" message should be entirely ignored (as with the "SEARCHING" message) or throw an according BusInitException. If this test is a valid scenario then the message BUS INIT has not been handled properly in the past. There shall only be two modes of handling 

1. remove message on reading the response
or 
2. throw exception

This test implies that there is a "silently ignore" magic?

**Comment by pires** [comment] 2015-07-15 16:14
@anti43 please run the tests before new PRs. `mvn clean test`. #43 is not working.

**Comment by anti43** [comment] 2015-07-15 16:19
@pires yes probably, as I wrote it was just a quick guess as grounds for discussion.
I did not try this, I just wanted to show you the problem. OK I agree, PR is not a good way to do this, sorry if this was not clear!

**Comment by anti43** [comment] 2015-07-15 16:28
@pires test pass now.
Sorry again:) next time iI use a patch not a PR for untested code
.

https://github.com/pires/obd-java-api/pull/44

**Closed** 2015-07-15 16:36 UTC
Labels: feature

**Comment by nomwerp** [comment] 2015-07-15 18:06
sorry to be a pain but i'm with RC3 i'm still getting 7F0912..
![screenshot_2015-07-15-19-57-54](https://cloud.githubusercontent.com/assets/10109262/8705865/b0cd3cf2-2b2c-11e5-857b-95be8797976d.png)
..but the unsupported commands now return "7F0112" instead of "7F 01 12"

**Comment by nomwerp** [comment] 2015-07-15 19:50
just checked the raw response is also `7F 09 12 \r\r` so nothing getting lost later

**Comment by anti43** [comment] 2015-07-15 20:50
@pires I suggest to add this

https://github.com/anti43/obd-java-api/blob/master/src/main/java/pt/lighthouselabs/obd/exceptions/UnsupportedCommandException.java

which works for 01 commands. for the 09 commands, this should support 7F0912 as well. so probably a generic UnsupportedCommandException matching a regex for 7F0[0-9]12 should handle this well.

@nomwerp 7F means "not supported" basically.

**Comment by pires** [comment] 2015-07-15 21:40
@anti43 awesome! Thank you.

@nomwerp would you be able to implement a workaround on `android-obd-reader` code to just print `NO DATA` when `7F 09 12` is the command result?

**Comment by nomwerp** [comment] 2015-07-16 06:26
thanks , so not a bug after all ;)
